<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)\IncreaseClimbHeight\$(TargetFileName)&quot;&#xD;&#xA;xcopy &quot;$(ProjectDir)\IncreaseClimbHeight\config.json&quot; &quot;$(ProjectDir)\..\..\SPT\user\mods\IncreaseClimbHeight\&quot; /Y /I" />
  </Target>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    <PackageReference Include="SemanticVersioning" Version="3.0.0" />
  </ItemGroup>
</Project>
